//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryStation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryStation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derek H. Osborne.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batteries.sqlite.
        /// </summary>
        internal static string BatteryDatabaseName {
            get {
                return ResourceManager.GetString("BatteryDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batteries.
        /// </summary>
        internal static string BatteryTableName {
            get {
                return ResourceManager.GetString("BatteryTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string ChargingStationTableName {
            get {
                return ResourceManager.GetString("ChargingStationTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to derek.osborne@ga-si.com.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Batteries (part_number TEXT NOT NULL, Revision TEXT NOT NULL, serial_number TEXT PRIMARY KEY NOT NULL UNIQUE, is_active INTEGER);.
        /// </summary>
        internal static string CreateBatteriesTable {
            get {
                return ResourceManager.GetString("CreateBatteriesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Stations (id INTERGER PRIMARY KEY AUTOINCREMENT ,battery_a TEXT, battery_b TEXT, state TEXT, state_changed TEXT);.
        /// </summary>
        internal static string CreateStationsTable {
            get {
                return ResourceManager.GetString("CreateStationsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=Batteries.sqlite;Version=3; failIfMissing=True.
        /// </summary>
        internal static string DatabaseConnection {
            get {
                return ResourceManager.GetString("DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * from `batteries`;.
        /// </summary>
        internal static string GetAllBatteries {
            get {
                return ResourceManager.GetString("GetAllBatteries", resourceCulture);
            }
        }
    }
}
